import {
  Baby,
  Banknote,
  Book,
  Bus,
  Car,
  Coffee,
  CreditCard,
  Dumbbell,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  Home,
  type LucideIcon,
  Music,
  PawPrint,
  Phone,
  Plane,
  Receipt,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Stethoscope,
  Tag,
  Tv,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  coffee: Coffee,
  food: Utensils,
  groceries: ShoppingCart,
  shopping: ShoppingBag,
  home: Home,
  car: Car,
  fuel: Fuel,
  bus: Bus,
  wifi: Wifi,
  electricity: Zap,
  phone: Phone,
  smartphone: Smartphone,
  tv: Tv,
  music: Music,
  film: Film,
  game: Gamepad2,
  gift: Gift,
  health: Stethoscope,
  fitness: Dumbbell,
  clothes: Shirt,
  travel: Plane,
  education: GraduationCap,
  book: Book,
  pet: PawPrint,
  baby: Baby,
  wrench: Wrench,
  card: CreditCard,
  cash: Banknote,
  wallet: Wallet,
  receipt: Receipt,
  heart: Heart,
  sparkles: Sparkles,
  other: Tag,
}

export const ICON_KEYS = Object.keys(ICONS)

export const DEFAULT_ICON = 'other'

export const COLOR_SWATCHES = [
  '#3fbf6f',
  '#e35c4d',
  '#4a90e2',
  '#f5a623',
  '#9b59b6',
  '#16a3a8',
  '#e0559c',
  '#8a8a86',
  '#c0392b',
  '#2e7d32',
]

export const DEFAULT_COLOR = COLOR_SWATCHES[0]
